apiVersion: apps/v1
kind: Deployment
metadata:
  name: experts-api-deployment
  labels:
    app: expertsservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: experts-api
  template:
    metadata:
      labels:
        app: experts-api
    spec:
      containers:
      - name: experts-api
        image: dave02081981/expertsservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
